name: Notify parent repo

on:
  push:
    branches:
      - main

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger musicdle-docker update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PARENT_REPO_TOKEN }}
          repository: eliott-colin/musicdle-docker
          event-type: submodule-update